variables:
  # Your GitLab host.
  GITLAB_HOST: "gitlab.ru"
  # Your GitLab committer username.
  USER_NAME: "Gitlab CI"
  # Your GitLab committer email.
  USER_EMAIL: "cicd@gitlab.ru"
  # Your GitLab repository URL.
  REPOSITORY: git@gitlab.ru:user/repository_name

stages:
    - compile
     
compile:
    stage: compile
    environment:
        name: master
    script:
      - docker run
        --rm
        -v $PWD:/app
        -e "SSH_PRIVATE_KEY=$SSH_PRIVATE_KEY"
        -e "CI_COMMIT_TAG=$CI_COMMIT_TAG"
        shitovdm/grpc-go:0.2.0
        /bin/sh -c
        'mkdir -p ~/.ssh &&
        echo "$SSH_PRIVATE_KEY" | tr -d "\r" > ~/.ssh/id_rsa &&
        chmod 600 ~/.ssh/id_rsa &&
        ssh-keyscan -H "$GITLAB_HOST" >> ~/.ssh/known_hosts &&
        cd /app &&
        git config --system core.fscache false &&
        git config --global http.sslVerify false &&
        git config --global user.name "$USER_NAME" &&
        git config --global user.email "$USER_EMAIL" &&
        git checkout master &&
        git fetch --all &&
        git reset --hard origin/master &&
        protoc --go_out=paths=source_relative:. ./proto/*/*.proto &&
        protoc --go-grpc_out=paths=source_relative:. ./proto/*/*.proto &&
        git add . &&
        git commit -m "Auto compile proto files >> v$CI_COMMIT_TAG" &&
        git push $REPOSITORY master &&
        git tag -a "v$CI_COMMIT_TAG" -m "Build tag v$CI_COMMIT_TAG" &&
        git push $REPOSITORY "v$CI_COMMIT_TAG"'
    only:
      - tags
    only:
      - /^[0-9]+(?:.[0-9]+)+$/
    except:
      - /^v[0-9]+(?:.[0-9]+)+$/
