name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Set output
        id: vars
        run: |
          echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
          echo ::set-output name=tag2::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}   
      - name: Build the tagged Docker image
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
          echo ${{ steps.vars.outputs.tag2 }}
          docker build . --file Dockerfile --tag shitovdm/grpc-go:$RELEASE_VERSION
      - name: Push the tagged Docker image
        run: docker push shitovdm/grpc-g:$RELEASE_VERSION
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag shitovdm/grpc-g:latest
      - name: Push the latest Docker image
        run: docker push shitovdm/grpc-g:latest

